In [1]:
import torch
print(torch.__version__)
import tensorboard
print(tensorboard.__version__)
# import torch.nn
from torch import nn
from torch.utils.tensorboard import SummaryWriter
from ipywidgets import IntProgress
import sys

2.2.2
2.6.0


In [6]:
print( torch.cuda.is_available())
print(sys.executable)
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print("device: ", device)

False
C:\ProgramData\anaconda3\python.exe


RuntimeError: Invalid device string: 'C:\Python312\python.exe'

In [30]:
# !jupyter nbextension enable --py widgetsnbextension

In [31]:
# zeros
X = torch.zeros(2,3)
print("zeros:", X)
X = torch.ones(2,3)
print('ones:',X)

zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [32]:
# change the shape X 2*3
X.view(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [33]:
## move tensor to data cpu or arracy, save to txt file
X.data.cpu()[0][0].item()  #[1]
X.data.cpu().numpy() #[[1,2],[2,3]],[1,2,3,4]

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
X = torch.rand(1)
print("X:",X)
X.data.cpu().item()
# X.item()


X: tensor([0.8833])


0.883281409740448

In [35]:
# flatten tensor
# torch.flatten(X,start_dim=0)
X = torch.rand(2,3)
print("X:",X)
torch.flatten(X,start_dim=0)


X: tensor([[0.4646, 0.6415, 0.5619],
        [0.6954, 0.8453, 0.8024]])


tensor([0.4646, 0.6415, 0.5619, 0.6954, 0.8453, 0.8024])

In [36]:
## tensor size
X.size()

torch.Size([2, 3])

In [37]:
## data loader
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torchvision
import h5py
rotation =10

def _load_data(DATA_PATH, batch_size):
    '''Data loader'''
    print("data_path: ", DATA_PATH)
    train_trans = transforms.Compose([transforms.RandomRotation(rotation),transforms.RandomHorizontalFlip(),\
                                      transforms.ToTensor(), transforms.Normalize((0.5), (0.5))])
    
    train_dataset = torchvision.datasets.MNIST(root=DATA_PATH, download=True,train=True, transform=train_trans)
    train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True,num_workers=8)
    ## for testing
    test_trans = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5), (0.5))])
    test_dataset = torchvision.datasets.MNIST(root=DATA_PATH, download=True, train=False, transform=test_trans)
    test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False, num_workers=8)
    return train_loader, test_loader

In [38]:
DATA_PATH = "./data/"
batch_size = 100
train_loader, test_loader = _load_data(DATA_PATH, batch_size)
for data,label in train_loader:
    print(label)
    break
    

data_path:  ./data/
tensor([6, 9, 3, 7, 1, 7, 8, 8, 2, 5, 5, 6, 3, 0, 1, 4, 9, 0, 8, 6, 1, 5, 9, 2,
        3, 8, 9, 2, 1, 9, 6, 9, 0, 0, 6, 3, 7, 8, 7, 3, 9, 2, 9, 0, 7, 2, 8, 5,
        0, 1, 2, 7, 7, 0, 1, 8, 6, 6, 1, 1, 8, 2, 6, 5, 1, 1, 7, 1, 8, 8, 8, 1,
        3, 5, 8, 3, 7, 3, 5, 1, 7, 9, 0, 6, 1, 5, 7, 0, 9, 6, 8, 6, 0, 0, 7, 9,
        1, 9, 5, 4])


In [39]:
## Method 1
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.FC1 = nn.Linear(28,30) ## fully connected layer
        act = nn.ReLU()  ## activation fun
        drop = nn.Dropout(p=0.2)  ## dropout
        self.FC2 = nn.Linear(30,10) ## fully connected layer
#         act = nn.ReLU()  ## activation fun
    ## feed data to the model
    def forward(self,x):
        h = self.FC1(x)
        h = self.act(h)
        h = self.drop(h)
        y_out = self.FC2(h)

In [40]:
## Method 2
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.Sequential(nn.Linear(28*28,50),
                                    nn.ReLU(),
                                    nn.Dropout(0.2),
                                    nn.Linear(50,20),
                                    nn.ReLU(),
                                    nn.Dropout(0.2),
                                    nn.Linear(20,10))
    ## feed data into the model
    def forward(self,x):
        y_out = self.layers(x)

In [41]:
## tensorboard
writer = SummaryWriter()
loss1 = 10
n_iter1 = 1

loss2 = 5
n_iter2 = 2

# loss3 = 1
# n_iter3 = 3

writer.add_scalar('Loss/train', loss1, n_iter1)
writer.add_scalar('Loss/train', loss2, n_iter2)
# writer.add_scalar('Loss/train', loss3, n_iter3)

In [42]:
## find the training curve locally
# http://localhost:6006/